/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => JpBooksPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  folderPath: "",
  fileNameFormat: "{{title}}",
  template: `---
title: "{{title}}"
author: "{{author}}"
publisher: "{{publisher}}"
published: {{published}}
isbn: "{{isbn}}"
tags:
  - \u8AAD\u66F8\u30CE\u30FC\u30C8
created: {{DATE}}
---

## \u5185\u5BB9\u7D39\u4ECB

{{description}}

## \u30E1\u30E2

`
};
var JpBooksSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "JpBooks \u8A2D\u5B9A" });
    new import_obsidian.Setting(containerEl).setName("\u4FDD\u5B58\u5148\u30D5\u30A9\u30EB\u30C0").setDesc("\u65B0\u898F\u30CE\u30FC\u30C8\u3092\u4F5C\u6210\u3059\u308B\u30D5\u30A9\u30EB\u30C0\u306E\u30D1\u30B9\uFF08\u7A7A\u767D\u306E\u5834\u5408\u306FVault\u30EB\u30FC\u30C8\uFF09").addText(
      (text) => text.setPlaceholder("\u4F8B: Books/\u8AAD\u66F8\u30CE\u30FC\u30C8").setValue(this.plugin.settings.folderPath).onChange(async (value) => {
        this.plugin.settings.folderPath = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u30D5\u30A1\u30A4\u30EB\u540D\u30D5\u30A9\u30FC\u30DE\u30C3\u30C8").setDesc("{{title}} / {{author}} / {{DATE}} / {{DATE:YYYYMMDD}} \u306A\u3069\u304C\u4F7F\u7528\u3067\u304D\u307E\u3059").addText(
      (text) => text.setPlaceholder("{{title}}").setValue(this.plugin.settings.fileNameFormat).onChange(async (value) => {
        this.plugin.settings.fileNameFormat = value || "{{title}}";
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u30CE\u30FC\u30C8\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8" });
    const details = containerEl.createEl("details");
    details.style.marginBottom = "8px";
    details.style.fontSize = "13px";
    const summary = details.createEl("summary", { text: "\u4F7F\u7528\u53EF\u80FD\u306A\u5909\u6570\u4E00\u89A7" });
    summary.style.cursor = "pointer";
    summary.style.color = "var(--text-muted)";
    const table = details.createEl("table");
    table.style.width = "100%";
    table.style.borderCollapse = "collapse";
    table.style.marginTop = "6px";
    table.style.fontSize = "12px";
    const vars = [
      ["{{title}}", "\u66F8\u540D"],
      ["{{subtitle}}", "\u526F\u984C"],
      ["{{author}}", "\u8457\u8005\u540D\uFF08\u30AB\u30F3\u30DE\u533A\u5207\u308A\uFF09"],
      ["{{authors}}", "\u8457\u8005\u540D\uFF08\u914D\u5217\u5F62\u5F0F\uFF09"],
      ["{{publisher}}", "\u51FA\u7248\u793E"],
      ["{{published}}", "\u51FA\u7248\u5E74\u6708\u65E5"],
      ["{{isbn}}", "ISBN-13"],
      ["{{description}}", "\u5185\u5BB9\u7D39\u4ECB"],
      ["{{DATE}}", "\u4F5C\u6210\u65E5\uFF08YYYY-MM-DD\uFF09"],
      ["{{DATE:FORMAT}}", "\u4F5C\u6210\u65E5\uFF08\u66F8\u5F0F\u6307\u5B9A\u3001\u4F8B: YYYYMMDD\uFF09"]
    ];
    for (const [varName, desc] of vars) {
      const tr = table.createEl("tr");
      const td1 = tr.createEl("td", { text: varName });
      const td2 = tr.createEl("td", { text: desc });
      td1.style.fontFamily = "monospace";
      td1.style.padding = "2px 12px 2px 0";
      td1.style.whiteSpace = "nowrap";
      td1.style.color = "var(--text-accent)";
      td2.style.color = "var(--text-muted)";
    }
    const textareaEl = containerEl.createEl("textarea");
    textareaEl.value = this.plugin.settings.template;
    textareaEl.rows = 20;
    textareaEl.style.width = "100%";
    textareaEl.style.boxSizing = "border-box";
    textareaEl.style.fontFamily = "monospace";
    textareaEl.style.fontSize = "13px";
    textareaEl.style.lineHeight = "1.6";
    textareaEl.style.whiteSpace = "pre";
    textareaEl.style.overflowX = "auto";
    textareaEl.style.resize = "vertical";
    textareaEl.style.padding = "8px";
    textareaEl.style.borderRadius = "4px";
    textareaEl.style.border = "1px solid var(--background-modifier-border)";
    textareaEl.style.background = "var(--background-primary)";
    textareaEl.style.color = "var(--text-normal)";
    textareaEl.addEventListener("input", async () => {
      this.plugin.settings.template = textareaEl.value;
      await this.plugin.saveSettings();
    });
    new import_obsidian.Setting(containerEl).setName("\u30C6\u30F3\u30D7\u30EC\u30FC\u30C8\u3092\u30C7\u30D5\u30A9\u30EB\u30C8\u306B\u623B\u3059").addButton(
      (btn) => btn.setButtonText("\u30EA\u30BB\u30C3\u30C8").setWarning().onClick(async () => {
        this.plugin.settings.template = DEFAULT_SETTINGS.template;
        await this.plugin.saveSettings();
        this.display();
      })
    );
  }
};

// src/modals/BookSearchModal.ts
var import_obsidian4 = require("obsidian");

// src/api/openbd.ts
var import_obsidian2 = require("obsidian");
async function fetchFromOpenBD(isbn) {
  var _a, _b, _c;
  try {
    const response = await (0, import_obsidian2.requestUrl)({
      url: `https://api.openbd.jp/v1/get?isbn=${isbn}`,
      method: "GET"
    });
    const data = response.json;
    if (!Array.isArray(data) || !data[0])
      return null;
    const item = data[0];
    const summary = item.summary;
    const detail = (_a = item.onix) == null ? void 0 : _a.DescriptiveDetail;
    const collateralDetail = (_b = item.onix) == null ? void 0 : _b.CollateralDetail;
    if (!(summary == null ? void 0 : summary.title))
      return null;
    const contributors = [];
    if (detail == null ? void 0 : detail.Contributor) {
      for (const c of detail.Contributor) {
        const name = ((_c = c.PersonName) == null ? void 0 : _c.content) || c.PersonName;
        if (name)
          contributors.push(String(name));
      }
    }
    if (contributors.length === 0 && summary.author) {
      contributors.push(summary.author);
    }
    let description = "";
    if (collateralDetail == null ? void 0 : collateralDetail.TextContent) {
      for (const tc of collateralDetail.TextContent) {
        if (tc.Text) {
          description = tc.Text;
          break;
        }
      }
    }
    const rawDate = summary.pubdate || "";
    const published = normalizeDate(rawDate);
    return {
      title: summary.title,
      subtitle: summary.subtitle || "",
      author: contributors.join(", "),
      authors: contributors,
      publisher: summary.publisher || "",
      published,
      isbn: summary.isbn || isbn,
      description
    };
  } catch (e) {
    console.error("[JpBooks] openBD error:", e);
    return null;
  }
}
function normalizeDate(raw) {
  const s = raw.replace(/\D/g, "");
  if (s.length >= 8)
    return `${s.slice(0, 4)}-${s.slice(4, 6)}-${s.slice(6, 8)}`;
  if (s.length >= 6)
    return `${s.slice(0, 4)}-${s.slice(4, 6)}`;
  if (s.length >= 4)
    return s.slice(0, 4);
  return raw;
}

// src/api/ndl.ts
var import_obsidian3 = require("obsidian");
async function fetchFromNDL(query, isIsbn = false) {
  var _a;
  try {
    const param = isIsbn ? `isbn=${encodeURIComponent(query)}` : `title=${encodeURIComponent(query)}`;
    const url = `https://ndlsearch.ndl.go.jp/api/opensearch?${param}&cnt=20`;
    const response = await (0, import_obsidian3.requestUrl)({ url, method: "GET" });
    const text = response.text;
    const parser = new DOMParser();
    const xml = parser.parseFromString(text, "application/xml");
    const parseError = xml.querySelector("parsererror");
    if (parseError) {
      console.error("[JpBooks] NDL XML parse error");
      return [];
    }
    const items = xml.getElementsByTagName("item");
    const results = [];
    for (const item of Array.from(items)) {
      const categories = Array.from(item.getElementsByTagName("category")).map((el) => {
        var _a2;
        return ((_a2 = el.textContent) == null ? void 0 : _a2.trim()) || "";
      });
      if (!categories.includes("\u56F3\u66F8"))
        continue;
      const title = getTagText(item, "dc:title") || getTagText(item, "title");
      if (!title)
        continue;
      const creatorEls = item.getElementsByTagName("dc:creator");
      let authors = Array.from(creatorEls).map((el) => {
        var _a2;
        return ((_a2 = el.textContent) == null ? void 0 : _a2.trim()) || "";
      }).filter(Boolean);
      if (authors.length === 0) {
        const authorText = getTagText(item, "author");
        if (authorText)
          authors = [authorText];
      }
      let isbn = "";
      const identifiers = Array.from(item.getElementsByTagName("dc:identifier"));
      for (const el of identifiers) {
        const type = el.getAttribute("xsi:type") || "";
        if (type === "dcndl:ISBN") {
          isbn = ((_a = el.textContent) == null ? void 0 : _a.trim().replace(/-/g, "")) || "";
          break;
        }
      }
      const publisher = getTagText(item, "dc:publisher");
      const rawDate = getTagText(item, "dc:date");
      const published = normalizeDate2(rawDate);
      const descEls = Array.from(item.getElementsByTagName("dc:description"));
      const description = descEls.map((el) => {
        var _a2;
        return ((_a2 = el.textContent) == null ? void 0 : _a2.trim()) || "";
      }).find((t) => t.length > 5 && !/^\d{4}$/.test(t)) || "";
      results.push({
        title,
        subtitle: "",
        author: authors.join(", "),
        authors,
        publisher,
        published,
        isbn,
        description
      });
    }
    return results;
  } catch (e) {
    console.error("[JpBooks] NDL error:", e);
    return [];
  }
}
function getTagText(el, tag) {
  var _a;
  const found = el.getElementsByTagName(tag);
  return found.length > 0 ? ((_a = found[0].textContent) == null ? void 0 : _a.trim()) || "" : "";
}
function normalizeDate2(raw) {
  const s = raw.replace(/\D/g, "");
  if (s.length >= 8)
    return `${s.slice(0, 4)}-${s.slice(4, 6)}-${s.slice(6, 8)}`;
  if (s.length >= 6)
    return `${s.slice(0, 4)}-${s.slice(4, 6)}`;
  if (s.length >= 4)
    return s.slice(0, 4);
  return raw;
}

// src/api/search.ts
var ISBN_REGEX = /^(97[89])?\d{9}[\dX]$/;
async function searchBooks(query) {
  const cleanQuery = query.trim().replace(/-/g, "");
  const isIsbn = ISBN_REGEX.test(cleanQuery);
  if (isIsbn) {
    return await searchByIsbn(cleanQuery);
  } else {
    return await searchByTitle(query.trim());
  }
}
async function searchByIsbn(isbn) {
  const openBDResult = await fetchFromOpenBD(isbn);
  if (openBDResult) {
    return [openBDResult];
  }
  console.log("[JpBooks] openBD miss, falling back to NDL...");
  const ndlResults = await fetchFromNDL(isbn, true);
  return ndlResults;
}
async function searchByTitle(title) {
  const openBDResults = await searchOpenBDByTitle(title);
  if (openBDResults.length > 0) {
    return openBDResults;
  }
  console.log("[JpBooks] openBD miss, falling back to NDL...");
  return await fetchFromNDL(title, false);
}
async function searchOpenBDByTitle(title) {
  const ndlCandidates = await fetchFromNDL(title, false);
  if (ndlCandidates.length === 0)
    return [];
  const results = [];
  for (const candidate of ndlCandidates.slice(0, 10)) {
    if (candidate.isbn) {
      const openBDDetail = await fetchFromOpenBD(candidate.isbn);
      if (openBDDetail) {
        results.push(openBDDetail);
        continue;
      }
    }
    results.push(candidate);
  }
  return results;
}

// src/modals/BookSearchModal.ts
var MIN_QUERY_LEN = 2;
var BookSearchModal = class extends import_obsidian4.Modal {
  constructor(app, onChoose) {
    super(app);
    this.books = [];
    this.selectedIndex = 0;
    this.isSearching = false;
    this.onChoose = onChoose;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("jpbooks-modal");
    contentEl.createEl("div", { text: "\u66F8\u7C4D\u3092\u691C\u7D22", cls: "jpbooks-modal-title" }).style.cssText = "font-size:16px;font-weight:bold;margin-bottom:12px;";
    this.inputEl = contentEl.createEl("input", {
      type: "text",
      placeholder: "\u66F8\u540D\u307E\u305F\u306FISBN\u3092\u5165\u529B\u3057\u3066Enter\u3067\u691C\u7D22"
    });
    this.inputEl.style.cssText = "width:100%;box-sizing:border-box;padding:8px;font-size:14px;border:1px solid var(--background-modifier-border);border-radius:4px;background:var(--background-primary);color:var(--text-normal);margin-bottom:8px;";
    this.statusEl = contentEl.createEl("div");
    this.statusEl.style.cssText = "font-size:12px;color:var(--text-muted);min-height:18px;margin-bottom:6px;";
    this.listEl = contentEl.createEl("div");
    this.listEl.style.cssText = "max-height:340px;overflow-y:auto;border:1px solid var(--background-modifier-border);border-radius:4px;display:none;";
    this.inputEl.addEventListener("keydown", (e) => this.handleKeyDown(e));
    this.inputEl.focus();
    const hint = contentEl.createEl("div", {
      text: "Enter: \u691C\u7D22 / \u2191\u2193: \u9078\u629E / esc: \u9589\u3058\u308B"
    });
    hint.style.cssText = "font-size:11px;color:var(--text-faint);margin-top:8px;text-align:center;";
  }
  async handleKeyDown(e) {
    if (e.key === "Enter") {
      e.preventDefault();
      e.stopPropagation();
      if (this.books.length > 0) {
        this.choose(this.books[this.selectedIndex]);
      } else {
        await this.runSearch();
      }
      return;
    }
    if (e.key === "ArrowDown") {
      e.preventDefault();
      this.moveSelection(1);
      return;
    }
    if (e.key === "ArrowUp") {
      e.preventDefault();
      this.moveSelection(-1);
      return;
    }
    if (e.key === "Escape") {
      this.close();
      return;
    }
    if (e.key.length === 1 || e.key === "Backspace") {
      this.clearResults();
    }
  }
  async runSearch() {
    const query = this.inputEl.value.trim();
    if (query.length < MIN_QUERY_LEN) {
      this.setStatus("2\u6587\u5B57\u4EE5\u4E0A\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044");
      return;
    }
    if (this.isSearching)
      return;
    this.isSearching = true;
    this.setStatus("\u691C\u7D22\u4E2D...");
    this.listEl.style.display = "none";
    try {
      this.books = await searchBooks(query);
      this.selectedIndex = 0;
      if (this.books.length === 0) {
        this.setStatus("\u66F8\u7C4D\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3067\u3057\u305F");
        this.listEl.style.display = "none";
      } else {
        this.setStatus(`${this.books.length}\u4EF6\u898B\u3064\u304B\u308A\u307E\u3057\u305F\u3002\u2191\u2193\u3067\u9078\u629E\u3057\u3066Enter\u3067\u6C7A\u5B9A`);
        this.renderList();
      }
    } catch (e) {
      this.setStatus("\u30A8\u30E9\u30FC\u304C\u767A\u751F\u3057\u307E\u3057\u305F");
      new import_obsidian4.Notice("\u691C\u7D22\u4E2D\u306B\u30A8\u30E9\u30FC\u304C\u767A\u751F\u3057\u307E\u3057\u305F");
    } finally {
      this.isSearching = false;
    }
  }
  renderList() {
    this.listEl.empty();
    this.listEl.style.display = "block";
    this.books.forEach((book, i) => {
      const item = this.listEl.createEl("div");
      item.style.cssText = "padding:8px 12px;cursor:pointer;border-bottom:1px solid var(--background-modifier-border);";
      const titleEl = item.createEl("div", { text: book.title });
      titleEl.style.cssText = "font-weight:bold;margin-bottom:2px;";
      const parts = [];
      if (book.author)
        parts.push(book.author);
      if (book.publisher)
        parts.push(book.publisher);
      if (book.published)
        parts.push(book.published.slice(0, 4));
      const metaEl = item.createEl("div", { text: parts.join(" \xB7 ") });
      metaEl.style.cssText = "font-size:12px;color:var(--text-muted);";
      item.addEventListener("mouseenter", () => {
        this.selectedIndex = i;
        this.updateSelection(false);
      });
      item.addEventListener("click", () => this.choose(book));
      if (i === this.books.length - 1) {
        item.style.borderBottom = "none";
      }
    });
    this.updateSelection(false);
  }
  updateSelection(scroll = true) {
    const items = this.listEl.querySelectorAll("div");
    items.forEach((el, i) => {
      el.style.background = i === this.selectedIndex ? "var(--background-modifier-hover)" : "";
    });
    if (scroll) {
      const selected = items[this.selectedIndex];
      if (selected)
        selected.scrollIntoView({ block: "nearest" });
    }
  }
  moveSelection(delta) {
    if (this.books.length === 0)
      return;
    this.selectedIndex = Math.max(
      0,
      Math.min(this.books.length - 1, this.selectedIndex + delta)
    );
    this.updateSelection(true);
  }
  choose(book) {
    this.close();
    this.onChoose(book);
  }
  clearResults() {
    this.books = [];
    this.selectedIndex = 0;
    this.listEl.style.display = "none";
    this.listEl.empty();
    this.setStatus("Enter\u3067\u691C\u7D22");
  }
  setStatus(text) {
    this.statusEl.textContent = text;
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/utils/template.ts
var import_obsidian5 = require("obsidian");
function renderTemplate(template, book) {
  let result = template;
  result = result.replace(/\{\{DATE:([^}]+)\}\}/g, (_, fmt) => {
    return (0, import_obsidian5.moment)().format(fmt);
  });
  result = result.replace(/\{\{DATE\}\}/g, () => {
    return (0, import_obsidian5.moment)().format("YYYY-MM-DD");
  });
  const vars = {
    title: book.title,
    subtitle: book.subtitle || "",
    author: book.author,
    authors: book.authors.map((a) => `"${a}"`).join(", "),
    publisher: book.publisher,
    published: book.published,
    isbn: book.isbn,
    description: book.description
  };
  for (const [key, value] of Object.entries(vars)) {
    result = result.replace(new RegExp(`\\{\\{${key}\\}\\}`, "g"), value);
  }
  return result;
}
function renderFileName(format, book) {
  const rendered = renderTemplate(format, book);
  return rendered.replace(/[\\/:*?"<>|#^[\]]/g, "").trim();
}

// src/main.ts
var JpBooksPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new JpBooksSettingTab(this.app, this));
    this.addCommand({
      id: "search-and-insert",
      name: "Search and Insert",
      editorCallback: (editor, _view) => {
        new BookSearchModal(this.app, async (book) => {
          const content = renderTemplate(this.settings.template, book);
          editor.replaceSelection(content);
        }).open();
      }
    });
    this.addCommand({
      id: "create-new-note",
      name: "Create New Note",
      callback: () => {
        new BookSearchModal(this.app, async (book) => {
          await this.createBookNote(book);
        }).open();
      }
    });
    this.addRibbonIcon("book-open", "JpBooks: \u66F8\u7C4D\u30CE\u30FC\u30C8\u3092\u4F5C\u6210", () => {
      new BookSearchModal(this.app, async (book) => {
        await this.createBookNote(book);
      }).open();
    });
  }
  /**
   * 書籍ノートを新規作成する
   */
  async createBookNote(book) {
    const fileName = renderFileName(this.settings.fileNameFormat, book);
    const folderPath = this.settings.folderPath.trim();
    if (folderPath) {
      const folder = this.app.vault.getAbstractFileByPath((0, import_obsidian6.normalizePath)(folderPath));
      if (!folder) {
        await this.app.vault.createFolder((0, import_obsidian6.normalizePath)(folderPath));
      }
    }
    const filePath = (0, import_obsidian6.normalizePath)(
      folderPath ? `${folderPath}/${fileName}.md` : `${fileName}.md`
    );
    const existing = this.app.vault.getAbstractFileByPath(filePath);
    if (existing) {
      new import_obsidian6.Notice(`\u30CE\u30FC\u30C8\u304C\u65E2\u306B\u5B58\u5728\u3057\u307E\u3059: ${fileName}`);
      const leaf2 = this.app.workspace.getLeaf(false);
      await leaf2.openFile(existing);
      return;
    }
    const content = renderTemplate(this.settings.template, book);
    const file = await this.app.vault.create(filePath, content);
    new import_obsidian6.Notice(`\u30CE\u30FC\u30C8\u3092\u4F5C\u6210\u3057\u307E\u3057\u305F: ${fileName}`);
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(file);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
